### PR TITLE
implemented support for non circular holes

### PR DESCRIPTION
**Pull request by Rarder44**
#5

### CODE REVIEW

**Comment by Rarder44** [comment]
It would be nice to implement an automatic grouping of features in the timeline... but at the moment I don't have time...

**Comment by Rarder44** [comment]
I noticed that in geometryUtil I left some test functions (no longer used) commented.
If you are interested in them for some reason, keep them, otherwise you can safely remove them

**Comment by Finn2708** [comment]
Hey, 
thanks for the PR. 
I will review and test tomorrow :)

**Comment by Finn2708** [comment]
This is working great :) 

Some of the shapes I tested this with:
image

I have two minor issues:
1. Could you run some form of PEP8 compliant formatter (e.g. ruff, black, ...) to clean up the code?
2. Small bug with an irregular shape:
image
The tool would not create the desired feature at 0°, but any other angle seems to work fine:
image
I suspect this may have to do with the tolerance defined in the `profileHasLine` function, but I am not sure.

**Comment by Rarder44** [comment]
I tried to recreate the shape with the measurements described but it works for me even at 0°.

try to send me your file so I can do some tests.

image

**Comment by Finn2708** [comment]
Try this:
[Sample.zip](https://github.com/user-attachments/files/17085400/Sample.zip)

The file is a bit of a mess, the sketch in question is called `Middle Block`.

**Comment by Rarder44** [comment]
ok, I should have solved it (and used ruff)

**Comment by Finn2708** [comment]
Excellent, also works on my end. 
Thanks you :)

**Pull request merged**
